# mappings.py

# Procedure name mapping: SQL procedure name -> list of mapped PG procedure names
PROCEDURE_NAME_MAP = {
    #TRAC Customised Procedures List ---------------------------------------------
    'sps_ESTAT_GetWorklistAccounts_AccountBalanceDriven_CustomDisplayConfig_RCW': ['sps_getworklistaccount_controllingbalancedriven_customdisplay'],
    'sps_ESTAT_GetWorklistAccounts_ControllingBalanceDriven_CustomDisplayConfig_RCW': ['sps_getworklistaccounts_accountbalancedriven_customdisplay'],
    'spf_SharedMinorFinancialClasses_MajorFinaincailClassCode_FillList': ['spf_sharedminorfinancialclasses_majorfinaincailclasscode_fillli'],
    'spf_STATActivityMessagesAssignments_cboActivityMessages_FillList': ['spf_statactivitymessagesassignments_cboactivitymessages_fillist'],
    'spf_STATFollowupActivityAdjustments_SAGrid20_STAT_ActivityCategories': ['spf_statfollowupactivityadjustments_sagrid20_stat_activitycateg'],
    'spf_STATPayorStatusAutocodeAssignmentsCriteria_SAGrid17_FillGrid': ['spf_statpayorstatusautocodeassignmentscriteria_fillgrid'],
    'spf_STATPayorStatusAutocodeAssignmentsCriteria_SAGrid17_InsertGrid': ['spf_statpayorstatusautocodeassignmentscriteria_insertgrid'],
    'spf_STATPayorStatusAutocodeAssignmentsCriteria_SAGrid17_UpdateGrid': ['spf_statpayorstatusautocodeassignmentscriteria_updategrid'],
    'spf_STATTaskTypeAssignments_SAGrid17_CriteriaCombo_WithLastActivity': ['spf_stattasktypeassignments_sagrid17_criteriacombo_withlastacti'],
    'spf_SummaryWeeklyFollowupWIPAdjustments_cboDollarStrata_FillList': ['spf_summaryweeklyfollowupwipadjustments_cbodollarstrata_filllis'],
    'spf_SUMMTrends_OutstandingVarianceByMajorFinancialClassGoals_Delete': ['spf_summtrends_outstandingvariancebymajfinclassgoal_delete'],
    'spf_SUMMTrends_OutstandingVarianceByMajorFinancialClassGoals_FillControl': ['spf_summtrends_outstandingvariancebymajfinclassgoal_fillcontrol'],
    'spf_SUMMTrends_OutstandingVarianceByMajorFinancialClassGoals_FillList': ['spf_summtrends_outstandingvariancebymajfinclassgoal_filllist'],
    'spf_SUMMTrends_OutstandingVarianceByMajorFinancialClassGoals_Insert': ['spf_summtrends_outstandingvariancebymajfinclassgoal_insert'],
    'spf_SUMMTrends_OutstandingVarianceByMajorFinancialClassGoals_Update': ['spf_summtrends_outstandingvariancebymajfinclassgoal_update'],
    'spf_SUMMTrends_OutstandingVarianceByMajorVarianceCodeGoals_Delete': ['spf_summtrends_outstandingvariancebymajvarcodegoal_delete'],
    'spf_SUMMTrends_OutstandingVarianceByMajorVarianceCodeGoals_FillControl': ['spf_summtrends_outstandingvariancebymajvarcodegoals_fillcontrol'],
    'spf_SUMMTrends_OutstandingVarianceByMajorVarianceCodeGoals_FillList': ['spf_summtrends_outstandingvariancebymajvarcodegoals_filllist'],
    'spf_SUMMTrends_OutstandingVarianceByMajorVarianceCodeGoals_Insert': ['spf_summtrends_outstandingvariancebymajvarcodegoals_insert'],
    'spf_SUMMTrends_OutstandingVarianceByMajorVarianceCodeGoals_Update': ['spf_summtrends_outstandingvariancebymajvarcodegoals_update'],
    'spf_SUMMTrends_VarianceAgeFromDischargeDate_cboDollarStrata_FillList': ['spf_summtrends_varianceagefromdischargedate_cbodollarstrata_fil'],
    'spf_SUMMTrends_WeeklyOccurrenceByMajorFinancialClassGoals_Delete': ['spf_summtrends_weeklyoccurrencebymajorfinancialclassgoals_delet'],
    'spf_SUMMTrends_WeeklyOccurrenceByMajorFinancialClassGoals_FillControl': ['spf_summtrends_weeklyoccurrencebymajorfinancialclassgoals_fillc'],
    'spf_SUMMTrends_WeeklyOccurrenceByMajorFinancialClassGoals_FillList': ['spf_summtrends_weeklyoccurrencebymajorfinancialclassgoals_filll'],
    'spf_SUMMTrends_WeeklyOccurrenceByMajorFinancialClassGoals_Insert': ['spf_summtrends_weeklyoccurrencebymajorfinancialclassgoals_inser'],
    'spf_SUMMTrends_WeeklyOccurrenceByMajorFinancialClassGoals_Update': ['spf_summtrends_weeklyoccurrencebymajorfinancialclassgoals_updat'],
    'spf_SUMMTrends_WeeklyOccurrenceByMajorVarianceCodeGoals_FillControl': ['spf_summtrends_weeklyoccurrencebymajorvariancecodegoals_fillcon'],
    'spf_SUMMTrends_WeeklyOccurrenceByMajorVarianceCodeGoals_FillList': ['spf_summtrends_weeklyoccurrencebymajorvariancecodegoals_filllis'],
    'spf_TRACTrendsFollowUpActivityBaselines_cboBaselineDate_Filllist': ['spf_tractrendsfollowupactivitybaselines_cbobaselinedate_filllis'],
    'spi_ESTAT_InsertQR_Tracking_UnacknowledgedAccountInsights_Activity': ['spi_estat_insertqr_tracking_unacknowledgedaccountinsights_activ'],
    #ONTRAC Customised Procedures List ---------------------------------------------
    'spf_ONTRACActivityStatusAssignment_ActivityStatusAssignmentCriteriaGrid_CriteriaName_FillCombo': ['spf_ontracactivitystatusassignment_cg_criterianame_fillcombo'],
            'spf_ONTRACActivityStatusAssignment_ActivityStatusAssignmentCriteriaGrid_DataType_FillCombo': ['spf_ontracactivitystatusassignment_cg_datatype_fillcombo'],
            'spf_ONTRACActivityStatusAssignment_ActivityStatusAssignmentCriteriaGrid_DeleteGrid': ['spf_ontracactivitystatusassignment_criteriagrid_deletegrid'],
            'spf_ONTRACActivityStatusAssignment_ActivityStatusAssignmentCriteriaGrid_FillGrid': ['spf_ontracactivitystatusassignment_criteriagrid_fillgrid'],
            'spf_ONTRACActivityStatusAssignment_ActivityStatusAssignmentCriteriaGrid_InsertGrid': ['spf_ontracactivitystatusassignment_criteriagrid_insertgrid'],
            'spf_ONTRACActivityStatusAssignment_ActivityStatusAssignmentCriteriaGrid_Operator_FillCombo': ['spf_ontracactivitystatusassignment_cg_operator_fillcombo'],
            'spf_ONTRACActivityStatusAssignment_ActivityStatusAssignmentCriteriaGrid_UpdateGrid': ['spf_ontracactivitystatusassignment_criteriagrid_updategrid'],
            'spf_ONTRACActivityStatusAssignment_ActivityStatusCombo_FillCombo': ['spf_ontracactivitystatusassignment_activitystatuscombo_fillcomb'],
            'spf_ONTRACCodes_CodeTypeAssignmentCriteriaGrid_CodeGroup_FillCombo': ['spf_ontraccodes_codetypeassignmentcriteriagrid_codegroup_fillco'],
            'spf_ONTRACCodes_CodeTypeAssignmentCriteriaGrid_CodeType_FillCombo': ['spf_ontraccodes_codetypeassignmentcriteriagrid_codetype_fillcom'],
            'spf_ONTRACExceptionAssignment_ExceptionAssignmentCriteriaGrid_CriteriaName_FillCombo': ['spf_ontracexceptionassignment_exceptionassignmentcriteriagrid_c'],
            'spf_ONTRACExceptionAssignment_ExceptionAssignmentCriteriaGrid_DataType_FillCombo': ['spf_ontracexceptionassignment_criteriagrid_datatypefillcombo'],
            'spf_ONTRACExceptionAssignment_ExceptionAssignmentCriteriaGrid_DeleteGrid': ['spf_ontracexceptionassignment_exceptionassignmentcriteriagrid_d'],
            'spf_ONTRACExceptionAssignment_ExceptionAssignmentCriteriaGrid_FillGrid': ['spf_ontracexceptionassignment_exceptionassignmentcriteriagrid_f'],
            'spf_ONTRACExceptionAssignment_ExceptionAssignmentCriteriaGrid_InsertGrid': ['spf_ontracexceptionassignment_exceptionassignmentcriteriagrid_i'],
            'spf_ONTRACExceptionAssignment_ExceptionAssignmentCriteriaGrid_Operator_FillCombo': ['spf_ontracexceptionassignment_exceptionassignmentcriteriagrid_o'],
            'spf_ONTRACExceptionAssignment_ExceptionAssignmentCriteriaGrid_UpdateGrid': ['spf_ontracexceptionassignment_exceptionassignmentcriteriagrid_u'],
            'spf_ONTRACMinorFinancialClassAssignments_CriteriaGrid_CriteriaName_FillCombo': ['spf_ontracminorfinancialclassassignments_criteriagrid_criterian'],
            'spf_ONTRACMinorFinancialClassAssignments_CriteriaGrid_DataType_FillCombo': ['spf_ontracminorfinancialclassassignments_criteriagrid_datatype_'],
            'spf_ONTRACMinorFinancialClassAssignments_CriteriaGrid_DeleteGrid': ['spf_ontracminorfinancialclassassignments_criteriagrid_deletegri'],
            'spf_ONTRACMinorFinancialClassAssignments_CriteriaGrid_InsertGrid': ['spf_ontracminorfinancialclassassignments_criteriagrid_insertgri'],
            'spf_ONTRACMinorFinancialClassAssignments_CriteriaGrid_Operator_FillCombo': ['spf_ontracminorfinancialclassassignments_criteriagrid_operator_'],
            'spf_ONTRACMinorFinancialClassAssignments_CriteriaGrid_UpdateGrid': ['spf_ontracminorfinancialclassassignments_criteriagrid_updategri'],
            'spf_ONTRACMinorFinancialClassAssignments_MinorFinancialClass_FillCombo': ['spf_ontracminorfinancialclassassignments_minorfinancialclass_fi'],
            'spf_ONTRACScopeAssignment_ScopeAssignmentCriteriaGrid_CriteriaName_FillCombo': ['spf_ontracscopeassignment_scopeassignmentcriteriagrid_criterian'],
            'spf_ONTRACScopeAssignment_ScopeAssignmentCriteriaGrid_DataType_FillCombo': ['spf_ontracscopeassignment_scopeassignmentcriteriagrid_datatype_'],
            'spf_ONTRACScopeAssignment_ScopeAssignmentCriteriaGrid_DeleteGrid': ['spf_ontracscopeassignment_scopeassignmentcriteriagrid_deletegri'],
            'spf_ONTRACScopeAssignment_ScopeAssignmentCriteriaGrid_InsertGrid': ['spf_ontracscopeassignment_scopeassignmentcriteriagrid_insertgri'],
            'spf_ONTRACScopeAssignment_ScopeAssignmentCriteriaGrid_Operator_FillCombo': ['spf_ontracscopeassignment_scopeassignmentcriteriagrid_operator_'],
            'spf_ONTRACScopeAssignment_ScopeAssignmentCriteriaGrid_UpdateGrid': ['spf_ontracscopeassignment_scopeassignmentcriteriagrid_updategri'],
            'spf_ONTRACUrgentAssignment_UrgentAssignmentCriteriaGrid_CriteriaName_FillCombo': ['spf_ontracurgentassignment_uacriteriagrid_criterianamefillcombo'],
            'spf_ONTRACUrgentAssignment_UrgentAssignmentCriteriaGrid_DataType_FillCombo': ['spf_ontracurgentassignment_uacriteriagrid_datatype_fillcombo'],
            'spf_ONTRACUrgentAssignment_UrgentAssignmentCriteriaGrid_DeleteGrid': ['spf_ontracurgentassignment_uacriteriagrid_deletegrid'],
            'spf_ONTRACUrgentAssignment_UrgentAssignmentCriteriaGrid_FillGrid': ['spf_ontracurgentassignment_uacriteriagrid_fillgrid'],
            'spf_ONTRACUrgentAssignment_UrgentAssignmentCriteriaGrid_InsertGrid': ['spf_ontracurgentassignment_uacriteriagrid_insertgrid'],
            'spf_ONTRACUrgentAssignment_UrgentAssignmentCriteriaGrid_Operator_FillCombo': ['spf_ontracurgentassignment_uacriteriagrid_operator_fillcombo'],
            'spf_ONTRACUrgentAssignment_UrgentAssignmentCriteriaGrid_UpdateGrid': ['spf_ontracurgentassignment_uacriteriagrid_updategrid'],
            'spf_ONTRACUrgentAssignment_UrgentAssignmentStatusCombo_FillCombo': ['spf_ontracurgentassignment_uastatuscombo_fillcombo'],
            'spf_ONTRACWorklistAssignment_WorklistAssignmentCriteriaGrid_CriteriaName_FillCombo': ['spf_ontracworklistassignment_worklistassignmentcriteriagrid_cri'],
            'spf_ONTRACWorklistAssignment_WorklistAssignmentCriteriaGrid_DataType_FillCombo': ['spf_ontracworklistassignment_worklistassignmentcriteriagrid_dat'],
            'spf_ONTRACWorklistAssignment_WorklistAssignmentCriteriaGrid_DeleteGrid': ['spf_ontracworklistassignment_worklistassignmentcriteriagrid_del'],
            'spf_ONTRACWorklistAssignment_WorklistAssignmentCriteriaGrid_FillGrid': ['spf_ontracworklistassignment_worklistassignmentcriteriagrid_fil'],
            'spf_ONTRACWorklistAssignment_WorklistAssignmentCriteriaGrid_InsertGrid': ['spf_ontracworklistassignment_worklistassignmentcriteriagrid_ins'],
            'spf_ONTRACWorklistAssignment_WorklistAssignmentCriteriaGrid_Operator_FillCombo': ['spf_ontracworklistassignment_worklistassignmentcriteriagrid_ope'],
            'spf_ONTRACWorklistAssignment_WorklistAssignmentCriteriaGrid_UpdateGrid': ['spf_ontracworklistassignment_worklistassignmentcriteriagrid_upd'],
            'spf_ONTRACWorklistExchanges_ExchangeFromGrid_AllowShares_FillCombo': ['spf_ontracworklistexchanges_exchangefromgrid_allowshares_fillco'],
            'spf_ONTRACWorklistExchanges_ExchangeFromGrid_AllowTransfers_FillCombo': ['spf_ontracworklistexchanges_exchangefromgrid_allowtransfers_fil'],
            'spf_ONTRACWorklistTypes_WorklistTypeGrid_ListingDisplay_FillCombo': ['spf_ontracworklisttypes_worklisttypegrid_listingdisplay_fillcom'],
            'spf_ONTRACWorklistTypes_WorklistTypeGrid_NewAccountDisplay_FillCombo': ['spf_ontracworklisttypes_worklisttypegrid_newaccountdisplay_fill']
       
    # ... (add all other mappings here as in your script) ...
}

# Event trigger name mapping: SQL event trigger name -> list of mapped PG event trigger names
EVENT_TRIGGER_NAME_MAP = {
    "ddlTrg_CreateTable_CreateHistory": ["ddl_create_table_create_history"],
    "ddlTrg_AlterTable_AlterHistory": ["evt_alter_table_history_sync"],
    "ddlTrg_DropTable_DropHistory": ["ddl_trg_drop_table_drop_history"],
    "LogDDLEvents": ["logddlevents_create_alter", "logddlevents_drop"],
    # ... (add all other mappings here as in your script) ...
}
